[versions]
kotlin = "1.8.22"
dokka = "1.8.20"

architectury-plugin = "3.4-SNAPSHOT"
architectury-loom = "0.12.0-SNAPSHOT"
shadow = "7.1.0"

guava = "31.1-jre"
crowdin = "1.0.2-SNAPSHOT"
toml4j = "0.7.2"
slf4j = "1.7.30"

spigot = "1.16.5-R0.1-SNAPSHOT"
folia = "1.20.1-R0.1-SNAPSHOT"
velocity = "3.1.1"
bungee = "1.19-R0.1-SNAPSHOT"

fabric-permissions = "0.2-SNAPSHOT"

[libraries]
guava        = { module = "com.google.guava:guava", version.ref = "guava" }
toml4j = { module = "com.moandjiezana.toml:toml4j", version.ref = "toml4j" }
slf4j        = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
crowdin = { module = "su.plo.crowdin:lib", version.ref = "crowdin" }

spigot = { module = "org.spigotmc:spigot-api", version.ref = "spigot" }
folia = { module = "dev.folia:folia-api", version.ref = "folia" }
velocity = { module = "com.velocitypowered:velocity-api", version.ref = "velocity" }
bungee-api = { module = "net.md-5:bungeecord-api", version.ref = "bungee" }
bungee-proxy = { module = "net.md-5:bungeecord-proxy", version.ref = "bungee" }

fabric-permissions = { module = "me.lucko:fabric-permissions-api", version.ref = "fabric-permissions" }

[plugins]
architectury-plugin = { id = "architectury-plugin", version.ref = "architectury-plugin" }
architectury-loom   = { id = "dev.architectury.loom", version.ref = "architectury-loom" }
shadow              = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
dokka               = { id = "org.jetbrains.dokka", version.ref = "dokka" }
